FROM public.ecr.aws/lambda/python:3.10.2023.08.02.10

COPY requirements.txt ${LAMBDA_TASK_ROOT}
COPY lambda_function.py ${LAMBDA_TASK_ROOT}
COPY botocore-1.29.140-py3-none-any.whl ${LAMBDA_TASK_ROOT}
COPY boto3-1.26.140-py3-none-any.whl ${LAMBDA_TASK_ROOT}

RUN pip install -r requirements.txt

CMD [ "lambda_function.handler" ]