FROM public.ecr.aws/lambda/python:3.10.2023.08.02.10

COPY requirements.txt ${LAMBDA_TASK_ROOT}
COPY askTitanVi.py ${LAMBDA_TASK_ROOT}
COPY ddbSession.py ${LAMBDA_TASK_ROOT}
COPY dependencies/boto* ${LAMBDA_TASK_ROOT}/

RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY index_faiss /opt/index_faiss

CMD [ "askTitanVi.lambda_handler" ]

