FROM public.ecr.aws/lambda/python:3.11

COPY requirements.txt ${LAMBDA_TASK_ROOT}
COPY dependencies/boto* ${LAMBDA_TASK_ROOT}/

RUN pip install --upgrade pip && pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY index_faiss /opt/index_faiss
COPY index_faiss_3 /opt/index_faiss_3
COPY index_faiss_5_embv2 /opt/index_faiss_5_embv2
COPY index_faiss_10_embv2 /opt/index_faiss_10_embv2
